import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import GoToTop from "@/components/GoToTop";
import Chatbox from "@/components/Chatbox";
import { Toaster } from "sonner";
import { organizationSchema } from "@/lib/schema";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Accordia Harmony | Youth Empowerment & Life Skills Training",
  description:
    "Accordia Harmony empowers young people with essential life skills, digital literacy, and confidence for independent living and career success.",
  keywords: [
    "youth empowerment",
    "life skills training",
    "digital literacy",
    "young people",
    "career development",
    "independent living",
    "youth organizations",
    "skills training",
    "UK youth programmes",
    "youth programs",
    "life skills",
    "vocational training",
    "career guidance",
    "youth development",
    "personal development",
    "confidence building",
    "communication skills",
    "leadership training",
    "professional skills",
    "employability skills",
    "job readiness",
    "work experience",
    "internships",
    "apprenticeships",
    "youth mentorship",
    "mentoring programs",
    "educational support",
    "academic support",
    "learning programs",
    "online learning",
    "digital skills",
    "technology training",
    "social skills",
    "wellbeing programs",
    "mental health support",
    "community engagement",
    "youth outreach",
    "social inclusion",
    "youth support services",
    "young adult training",
    "educational programs",
    "skill development",
    "teen programs",
    "adolescent development",
    "transition support",
    "school to work",
    "career pathways",
    "employment support",
    "job placement",
    "CV writing",
    "interview preparation",
    "public speaking",
    "teamwork skills",
    "problem solving",
    "critical thinking",
    "time management",
    "financial literacy",
    "budgeting skills",
    "money management",
    "life coaching",
    "personal coaching",
    "youth coaching",
    "positive development",
    "youth empowerment programs",
    "character development",
    "self-esteem building",
    "resilience training",
    "emotional intelligence",
    "conflict resolution",
    "peer support",
    "youth workshops",
    "training workshops",
    "community programs",
    "social learning",
    "collaborative learning",
    "practical training",
    "hands-on learning",
    "project-based learning",
    "experiential learning",
    "gamified learning",
    "interactive training",
    "online programs",
    "remote learning",
    "blended learning",
    "youth conferences",
    "seminars for youth",
    "webinars",
    "online workshops",
    "training events",
    "youth initiatives",
    "social enterprise",
    "community interest company",
    "CIC",
    "non-profit",
    "charity",
    "registered charity",
    "youth charity",
    "education charity",
    "social impact",
    "community impact",
    "sustainable development",
    "SDG",
    "equal opportunities",
    "inclusive education",
    "diversity and inclusion",
    "accessibility training",
    "neurodivergent support",
    "ADHD support",
    "autism support",
    "learning disabilities",
    "special educational needs",
    "SEN",
    "SEND",
    "first generation",
    "underrepresented communities",
    "disadvantaged youth",
    "vulnerable young people",
    "at-risk youth",
    "youth in care",
    "care leavers",
    "NEET programs",
    "NEET youth",
    "school leavers",
    "early leavers",
    "drop-out prevention",
    "youth retention",
    "engagement programs",
    "motivation programs",
    "aspirational support",
    "goal setting",
    "future planning",
    "life planning",
    "young professional development",
    "graduate support",
    "entry-level jobs",
    "junior positions",
    "career advancement",
    "professional networking",
    "networking events",
    "business skills",
    "entrepreneurship",
    "startup support",
    "business mentoring",
    "business coaching",
    "innovation training",
    "creative skills",
    "design thinking",
    "problem-based learning",
    "STEM training",
    "STEAM education",
    "coding bootcamp",
    "web development",
    "app development",
    "IT skills",
    "cybersecurity awareness",
    "digital citizenship",
    "online safety",
    "internet safety",
    "digital wellbeing",
    "screen time management",
    "social media literacy",
    "media literacy",
    "critical media consumption",
    "fake news awareness",
    "misinformation training",
    "health and wellbeing",
    "nutrition programs",
    "fitness programs",
    "mental wellbeing",
    "stress management",
    "anxiety support",
    "depression awareness",
    "suicide prevention",
    "self-harm prevention",
    "substance abuse prevention",
    "healthy lifestyles",
    "physical activity",
    "sports programs",
    "recreational activities",
    "arts programs",
    "music programs",
    "drama programs",
    "creative expression",
    "performing arts",
    "cultural programs",
    "heritage programs",
    "celebration of diversity",
    "multicultural programs",
    "interfaith dialogue",
    "community cohesion",
    "social cohesion",
    "citizenship education",
    "civic engagement",
    "voting education",
    "political participation",
    "democratic skills",
    "rights and responsibilities",
    "human rights",
    "equality training",
    "consent education",
    "healthy relationships",
    "sex education",
    "relationship guidance",
    "parenting support",
    "family support",
    "guardianship",
    "safeguarding",
    "child protection",
    "duty of care",
    "pastoral support",
    "welfare programs",
    "support services",
    "counseling services",
    "therapy services",
    "holistic support",
    "wrap-around support",
    "joined-up services",
    "multi-agency support",
    "partnership working",
    "collaborative approach",
    "evidence-based practice",
    "outcome measurement",
    "impact assessment",
    "program evaluation",
    "quality assurance",
    "continuous improvement",
    "best practice",
    "accreditation",
    "certified programs",
    "qualified trainers",
    "experienced staff",
    "expert facilitation",
    "professional development",
    "staff training",
    "CPD",
    "continuing professional development",
    "sector leadership",
    "innovation in education",
    "future skills",
    "21st century skills",
    "transferable skills",
    "soft skills",
    "hard skills",
    "technical skills",
    "metacognitive skills",
    "learning to learn",
    "reflection skills",
    "self-awareness",
    "cultural awareness",
    "global citizenship",
    "international perspective",
    "sustainability",
    "environmental awareness",
    "climate action",
    "social responsibility",
    "corporate social responsibility",
    "corporate partnerships",
    "employer partnerships",
    "school partnerships",
    "university partnerships",
    "cross-sector collaboration",
    "stakeholder engagement",
    "participant feedback",
    "user feedback",
    "testimonials",
    "success stories",
    "case studies",
    "participant outcomes",
    "achievement data",
    "progression data",
    "retention rates",
    "completion rates",
    "satisfaction rates",
    "Accordia Harmony",
    "Accordia",
    "Harmony programs",
    "UK based",
    "London based",
    "community interest company",
    "youth focused",
    "young person centered",
    "client-centered approach",
    "participant-led",
    "co-production",
    "service user involvement",
    "youth consultation",
    "youth voice",
    "authentic engagement",
    "meaning making",
    "cultural competence",
    "trauma-informed practice",
    "strengths-based approach",
    "asset-based approach",
    "positive youth development",
    "protective factors",
    "risk factors",
    "vulnerability assessment",
    "need analysis",
    "pathway planning",
    "transition planning",
    "resource planning",
    "financial planning",
    "access to funding",
    "scholarship programs",
    "bursaries",
    "grants",
    "funding opportunities",
    "affordable programs",
    "cost effective",
    "value for money",
    "flexible delivery",
    "blended delivery",
    "face to face",
    "virtual delivery",
    "hybrid delivery",
    "evening programs",
    "weekend programs",
    "holiday programs",
    "vacation programs",
    "summer programs",
    "school year programs",
    "year-round programs",
    "intensive programs",
    "short-term programs",
    "long-term programs",
    "modular programs",
    "accredited programs",
    "qualification pathways",
    "level 1",
    "level 2",
    "level 3",
    "NVQ programs",
    "BTEC programs",
    "GCSEs",
    "A-Levels",
    "degree programs",
  ],
  authors: [{ name: "Accordia Harmony C.I.C." }],
  creator: "Accordia Harmony",
  publisher: "Accordia Harmony C.I.C.",
  formatDetection: {
    email: true,
    telephone: true,
    address: true,
  },
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_GB",
    url: "https://www.accordiaharmony.org",
    siteName: "Accordia Harmony",
    title: "Accordia Harmony | Youth Empowerment & Life Skills Training",
    description:
      "Accordia Harmony empowers young people with essential life skills, digital literacy, and confidence for independent living and career success.",
    images: [
      {
        url: "https://www.accordiaharmony.org/images/og-image.png",
        width: 1200,
        height: 630,
        alt: "Accordia Harmony - Youth Empowerment",
        type: "image/png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@AccordiaHarmony",
    creator: "@AccordiaHarmony",
    title: "Accordia Harmony | Youth Empowerment & Life Skills Training",
    description:
      "Accordia Harmony empowers young people with essential life skills, digital literacy, and confidence for independent living and career success.",
    images: ["https://www.accordiaharmony.org/images/og-image.png"],
  },
  alternates: {
    canonical: "https://www.accordiaharmony.org",
  },
  metadataBase: new URL("https://www.accordiaharmony.org"),
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify(organizationSchema),
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#060610] text-white ${poppins.variable} overflow-x-hidden`}
      >
        <Toaster position="top-center" theme="dark" />
        {children}
        <GoToTop />
        <Chatbox />
        {/* <Footer /> */}
      </body>
    </html>
  );
}
